# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 03:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import keops.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', keops.models.fields.CharField(blank=True, max_length=256, null=True)),
                ('action_type', keops.models.fields.CharField(blank=True, editable=False, max_length=16, null=True)),
                ('usage', keops.models.fields.TextField(blank=True, null=True)),
                ('help', keops.models.fields.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', keops.models.fields.CharField(blank=True, max_length=128, null=True)),
                ('active', models.BooleanField(default=True, verbose_name='active')),
                ('sequence', keops.models.fields.IntegerField(blank=True, default=100, null=True)),
                ('icon', keops.models.fields.CharField(blank=True, max_length=256, null=True)),
                ('url', keops.models.fields.CharField(blank=True, max_length=512, null=True)),
            ],
            options={
                'ordering': ('sequence', 'parent_id', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', keops.models.fields.CharField(blank=True, max_length=256, null=True, unique=True)),
                ('model', keops.models.fields.CharField(blank=True, db_index=True, max_length=128, null=True)),
                ('active', models.BooleanField(db_index=True, verbose_name='Active')),
                ('domain', keops.models.fields.TextField(blank=True, null=True, verbose_name='Domain')),
                ('group', keops.models.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='Group')),
            ],
        ),
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Action')),
            ],
            bases=('base.action',),
        ),
        migrations.CreateModel(
            name='WindowAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Action')),
                ('domain', keops.models.fields.TextField(blank=True, null=True)),
                ('context', keops.models.fields.TextField(blank=True, null=True)),
                ('object_id', keops.models.fields.BigIntegerField(blank=True, null=True)),
                ('target', keops.models.fields.CharField(blank=True, choices=[('current', 'Current Window'), ('new', 'New')], default='current', max_length=16, null=True)),
                ('view_mode', keops.models.fields.CharField(blank=True, default='list,form', max_length=128, null=True)),
                ('view_type', keops.models.fields.CharField(blank=True, choices=[('list', 'List'), ('form', 'Form')], default='form', max_length=16, null=True)),
                ('limit', models.PositiveIntegerField(default=100)),
                ('filter', models.BooleanField(default=False)),
                ('auto_search', models.BooleanField(default=True)),
                ('model', keops.models.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
                ('source_model', keops.models.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.ContentType')),
            ],
            options={
                'db_table': 'base_window_action',
            },
            bases=('base.action',),
        ),
        migrations.AddField(
            model_name='menu',
            name='action',
            field=keops.models.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Action'),
        ),
        migrations.AddField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
        migrations.AddField(
            model_name='menu',
            name='parent',
            field=keops.models.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.Menu'),
        ),
    ]
