# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 19:23
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import keops.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('parent_id', 'id')},
        ),
        migrations.AddField(
            model_name='menu',
            name='url',
            field=keops.models.fields.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=keops.models.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.Menu'),
        ),
    ]
