# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20170107_1827'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('sequence', 'parent_id', 'id')},
        ),
        migrations.AlterField(
            model_name='menu',
            name='active',
            field=models.BooleanField(default=True, verbose_name='active'),
        ),
    ]
