# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 16:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import keops.models.fields


class Migration(migrations.Migration):

    dependencies = [
        #('keops', '0002_auto_20170107_1843'),
        ('base', '0005_auto_20170108_0135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.Action')),
                ('report', keops.models.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keops.Report')),
            ],
            bases=('base.action',),
        ),
        migrations.AlterField(
            model_name='menu',
            name='groups',
            field=models.ManyToManyField(blank=True, to='auth.Group'),
        ),
    ]
