# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-04 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import keops.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', keops.models.fields.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'keops_report',
            },
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', keops.models.fields.CharField(blank=True, max_length=256, null=True)),
                ('empresa_id', keops.models.fields.IntegerField(blank=True, null=True)),
                ('user_id', keops.models.fields.IntegerField(blank=True, null=True)),
                ('user_params', keops.models.fields.TextField(blank=True, null=True)),
            ],
            options={
                'managed': False,
                'db_table': 'keops_user_report',
            },
        ),
    ]
