# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-04-19 04:07
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import keops.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('keops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreport',
            name='report',
            field=keops.models.fields.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='keops.Report'),
        ),
    ]
